#' A Data set containing movies released in Hollywood from 1920 to 2016
#' 
#' Along with movie, and directors' names the dataset contains data about the cost, revenue generated by the movies too.
#'
#' @format A tibble with 243 rows and 10 variables:
#' \describe{
#'   \item{title}{character Name of the movies}
#'   \item{genre}{character Movie type or genre names} 
#'   \item{director}{character Name of the movie director}
#'   \item{year}{integer Year when the movie was released}
#'   \item{duration}{int Total length of the movie in minutes}
#'   \item{gross}{int Gross revenue generated by the movie}
#'   \item{budget}{int Total money invested to produce the movie}
#'   \item{cast_facebook_likes}{int Total number of facebook likes for the movie}
#'   \item{votes}{int Total number of votes for the movie}
#'   \item{reviews}{int Total number of reviews that exist for the movie}
#'   \item{rating}{num Average user rating of the movie}
#'   \item{profit}{int Gross - Budget}
#' }
#' @source \url{https://www.datacamp.com/}
#' 
"movies"